channels:
- conda-forge
dependencies:
- python=3.12.12
- pip<=25.3
- pip:
  - mlflow==2.22.4
  - cffi==2.0.0
  - cloudpickle==3.1.2
  - lightgbm==4.6.0
  - matplotlib==3.9.2
  - numpy==1.26.4
  - pandas==2.3.3
  - psutil==7.1.3
  - pyarrow==19.0.1
  - scikit-learn==1.8.0
  - scipy==1.13.1
name: mlflow-env
