artifact_location: /Users/Swaminathan/Desktop/all_code_base/eas503_final_project/housing_app_fall25/notebooks/dpg-d5256sv5r7bs739ugro0-a.ohio-postgres.render.com/412852327008676579
creation_time: 1766086676175
experiment_id: '412852327008676579'
last_update_time: 1766086676175
lifecycle_stage: active
name: telco_churn_baseline_experiments
